FROM ubuntu:focal
RUN apt-get update
RUN apt-get install curl -y
RUN curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
RUN chmod 500 nsolid_setup_deb.sh
RUN ./nsolid_setup_deb.sh 18
RUN apt-get install nodejs -y
RUN apt-get install unzip -y
RUN apt-get install git -y
RUN npm install -g @wavemaker/wm-reactnative-cli@1.5.4
